# Generated by Django 2.0.3 on 2018-03-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180309_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tagged_items', to='blog.Tag'),
        ),
    ]
