# Generated by Django 2.0.3 on 2018-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180309_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anon',
            field=models.BooleanField(default=False, verbose_name='ناشناس'),
        ),
    ]
